FROM node:22-alpine

WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante do código
COPY . .

# Gera o cliente do Prisma
RUN npx prisma generate

# Compila o código TypeScript
RUN npm run build

# Expõe a porta do backend
EXPOSE 3001

# Comando para rodar o servidor
CMD ["node", "src/server.js"]
